/**
 * angular-typescript-starter
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { USERTYPE } from './uSERTYPE';


/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickIUserFirstnameOrLastnameOrUsernameOrPasswordOrEmailOrUserType { 
    firstname: string;
    lastname: string;
    username: string;
    email: string;
    user_type: USERTYPE;
    password: string;
}

